### ISSUE TITLE
how to add fields to time-aware-template popup window?

### ISSUE THREAD

**Issue by JackDougherty** [Esri/time-aware-template#7]
Thanks for the July 2015 improvements to this ESRI time-aware-template, which I discovered today, and may help me with my time-slider project involving historical data. Using your template, I was able to fork a copy of your earthquake data sample (https://github.com/JackDougherty/time-aware-template/tree/gh-pages) and host a working demo on GitHub Pages (https://jackdougherty.github.io/time-aware-template/).

Question: Where do I modify the code to insert additional table fields (such as "time") in the popup window? See screenshot below.

![time-aware-template-popup-question](https://cloud.githubusercontent.com/assets/649719/8688901/6542bb9e-2a6f-11e5-8a83-77bcb9c3e60c.png)

**Comment by jgravois** [comment]
our ArcGIS Online templates are designed to be able to load different content dynamically.  this means that you'd make alterations to the popup content in the webmap that the application is loading, rather than the code of the application.

http://doc.arcgis.com/en/arcgis-online/create-maps/make-your-first-app.htm

**Comment by JackDougherty** [comment]
Now I understand the concept. This is very helpful.

**Comment by jgravois** [comment]
glad to hear it.
